# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: buycheap_development
  pool: 5
  username: postgres
  password: postgres