# you can find your token and api in https://desenvolvedor.moip.com.br/sandbox/AdmAPI.do?method=keys
development:
  uri: https://desenvolvedor.moip.com.br/sandbox
  token: LX5WC5DPCCYEBKCIPOVKOK9WN5K4PQPE
  key: HCXWRNQJXQJOBWU6PVBJNBW4HDUQZ6KQZBQ07MGE

test:
  uri: https://desenvolvedor.moip.com.br/sandbox
  token: YOUR_TOKEN
  key: YOUR_KEY

