development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/pedido/efetuado"
  email: diegosax@terra.com.br

test:
  <<: *development

production:
  authenticity_token: 959BD6FEF823427BBA29A29629D9426E
  email: diegosax@terra.com.br
  return_to: "http://buycheap.heroku.com/pedido/efetuado"
