development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/pedido/efetuado"
  email: diegosax@terra.com.br

test:
  <<: *development

production:
  authenticity_token: 0A15C8D670514BBF8A583497EDA1AD4B
  email: diegosax@terra.com.br
  return_to: "http://buycheap.heroku.com/pedido/efetuado"
